exp:
  name: mscmr-32_038
  names_exp_delete: null
  path_save: ./save
  idx_device: 0
  rand_seed: null
  n_workers: 16
  compile_model: false
  customize_dataloader: true
  train:
    path_model_trained: null
    epoch_start: 0
    n_epochs: 9999999
    batch_size: 60
    use_gradscaler: false
    save_best_model_on_test_set: false
    optimizer:
      name: adamw
      lr: 0.001
      adamw:
        weight_decay: 0.0001
    scheduler:
      name: null
  val:
    batch_size: 1
    skip_initial_val: true
    n_epochs_once: 1
    no_val_before_epoch: 0
    n_repeat: 1
    save_every_model: false
    save_every_better_model: false
    save_latest_model: true
    n_epoch_stop_after_not_better: 800
  test:
    batch_size: 1
    path_model_trained: null
    n_repeat: 1
  source_only: false
  mode: train
model:
  name: ours2
  qzxv:
    from: feat_reg
    based_on: atlas
  ws_loss:
    dice_ce: 1.0
    recon: 15.0
    recon_ncc: 0.0
    kl_v: 65.0
    v_domain_diff_region_wise: 0.0
    kl_z: 0.0
    kl_c_domain_diff: 0.002
    kl_c_sample_unif: 0.0
    kl_c_batch_unif: 0.0
    kl_c_sample_ent: 0.0
    c_domain_diff_batch_mean: 0.0
    c_domain_diff_batch_covar: 0.0
    kl_atlas_to_geomean: 0.0
    kl_atlas: 5.0
    adv_enc_feat: 0.0
    adv_seg: 0.0
    distance_qz: 0.0
    pos_slice: 0.0
    diff_qc_to_mask_sim: 1.0
    c_dispersity: 0.0
  losses:
    dice_ce:
      ws:
      - 1.0
      - 1.0
    ce:
      ws_class:
      - 1.0
      - 8.0
      - 2.0
      - 4.0
    recon:
      ws_domain:
      - 1.0
      - 1.0
      scale: learned
      include_bgs:
      - true
      - true
      bg_zeros:
      - false
      - false
    recon_ncc:
      ws_domain:
      - 1.0
      - 1.0
    kl_v:
      ws_domain:
      - 1.0
      - 1.0
    v_domain_diff_region_wise:
      subtract_mean: true
      method: sinkhorn
      blur: 0.2
    kl_z:
      ws_domain:
      - 1.0
      - 1.0
    kl_c_domain_diff:
      method: wasserstein
      wasserstein:
        logratio_transform: false
        blur: 0.3141593
      queue_size: 0
      cost: fisher_rao
    kl_c_sample_unif:
      ws_domain:
      - 1.0
      - 1.0
    kl_c_batch_unif:
      ws_domain:
      - 1.0
      - 1.0
    kl_c_sample_ent:
      ws_domain:
      - 1.0
      - 1.0
    distance_qz:
      based_on: feat
      levels:
      - 4
    pos_slice:
      ws_domain:
      - 1.0
      - 1.0
    adv_enc_feat:
      mode: levelwise
      levels:
      - 0
      - 1
      - 2
      - 3
      - 4
      alpha: 1.0
    adv_seg:
      alpha: 1.0
    diff_qc_to_mask_sim:
      ws_domain:
      - 1.0
      - 0.0
      distance_qc: fisher_rao
    c_dispersity:
      mode: det_euclidean
      ws_domain:
      - 1.0
      - 0.0
    kl_c:
      ws_domain:
      - 1.0
      - 1.0
dataset:
  name: mscmr
  version: 1.1
  n_classes: 4
  idx2name_class:
    '1': myo
    '2': LV
    '3': RV
  dim: 2
  hw_img: 192
  source:
    mod: C0
    range_idx:
      train: range(1, 36)
      val: range(36, 46)
      test: range(36, 46)
  target:
    mod: LGE
    range_idx:
      train: range(1, 46)
      val: range(1, 6)
      test: range(6, 46)
  preprocess:
    equalize: false
    normalize:
      enable: true
      wise: slice
      mode: min-max
  aug:
    crop: 160
    rand_bias_field:
      enable: false
      prob: 0.1
      coeff_range:
      - 0.1
      - 0.3
net:
  n_levels: 5
  encoder:
    channels: 16
    between_domains: same
    norm_type: instance
  decoder_rec:
    between_domains: same
    detach_decoder_input:
    - false
    - false
  net_c:
    between_domains: same
    dropout: 0.0
  reg:
    levels:
    - 0
    - 2
    - 4
    n_blocks:
    - 2
    - 2
    - 2
    between_domains: same
  style_code:
    enable: true
    mode: AdaIN
    adain:
      style_dim: 64
      classwise: false
  atlas:
    soft_idx: true
    soft_idx_add_noise:
      enable: false
      std: 0.02
    freeze_grad:
      enable: false
      mode: periodic
      periodic:
        period: 10
    num: 6
    n_samples: -1
    qc:
      calc:
        mode:
          name: net
        levelwise: false
        levels:
        - 4
        input_includes_atlas: false
